services:
  mysql:
    image: mysql:5.7
    container_name: starwars-api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - ./mysql:/var/lib/mysql