spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3308/db?useSSL=false&serverTimezone=UTC
      username: user
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

